########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 3/7/2018
#
# generic Gcc Makefile for numera Executable numera
########################################################################


#
# target
#
numera_exe_EXETARGET = numera

########################################################################

#
# user c++ flags
#
numera_exe_USRCXXFLAGS += \
${numera_USRCXXFLAGS} \

#
# user defines
#
numera_exe_USRDEFINES += \
${numera_USRDEFINES} \

#
# user includes
#
numera_exe_USRINCLUDES += \
${numera_USRINCLUDES} \

#
# user libdirs
#
numera_exe_USRLIBDIRS += \
${numera_USRLIBDIRS} \

########################################################################

#
# Executable .c sources
#
#numera_exe_EXE_C_SOURCES += \
#${NUMERA_SRC}/numera/base/Base.c \

#
# Executable .cc sources
#
#numera_exe_EXE_CC_SOURCES += \
#${NUMERA_SRC}/numera/base/Base.cc \

#
# Executable .cxx sources
#
#numera_exe_EXE_CXX_SOURCES += \
#${NUMERA_SRC}/numera/base/Base.cxx \

#
# Executable .cpp sources
#
numera_exe_EXE_CPP_SOURCES += \
${NUMERA_SRC}/numera/base/base.cpp \
${NUMERA_SRC}/numera/console/main_main.cpp \
${NUMERA_SRC}/numera/app/console/numera/main_opt.cpp \
${NUMERA_SRC}/numera/app/console/numera/main.cpp \

#
# Executable .m sources
#
#numera_exe_EXE_M_SOURCES += \
#${NUMERA_SRC}/numera/base/Base.m \

#
# Executable .mm sources
#
#numera_exe_EXE_MM_SOURCES += \
#${NUMERA_SRC}/numera/base/Base.mm \


########################################################################

#
# Executable libraries
#
numera_exe_LIBS += \
${numera_LIBS}



